# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = ENV['VAGRANT_BOX']
  config.vm.box_version = ENV['VAGRANT_BOX_VERSION']
  config.vm.define ENV['VAGRANT_SERVER_NAME']

  ## Configure shared folders
  config.vm.synced_folder "../_scripts", "/vagrant/scripts"
  # config.vm.synced_folder "~/path/to/host/directory", "/full/path/to/vm/directory"
  # config.vm.synced_folder "~/path/to/host/directory", "/home/vagrant/some-directory"

  ## Configure CPU count and RAM
  config.vm.provider "virtualbox" do |v|
    v.name = ENV['VAGRANT_SERVER_NAME']
    v.memory = ENV['VAGRANT_RAM']
    v.cpus = ENV['VAGRANT_CPUS']
  end

  ## Configure SSH
  config.ssh.forward_agent = true
  config.vm.network "forwarded_port", guest: 22, host: ENV["SSH_PORT"], id: "ssh"

  ## Configure forwarded ports
  # config.vm.network "forwarded_port", guest: 4000, host: 4000, id: "phoenix"

  ## These scripts will run automatically when the VM is first created. To run
  ## them again, run `vagrant provision`
  config.vm.provision "shell", path: "./provision-root.sh"
  config.vm.provision "shell", path: "./provision-user.sh", privileged: false
end
