Vagrant.configure("2") do |config|
  config.vm.provider :docker do |d|
     d.build_dir = "."
     d.remains_running = true
     d.has_ssh = true
  end

	# Provisioning configuration for Ansible.
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "playbook.yml"
	end

end
