Vagrant.configure("2") do |config|
  config.vm.box = ENV['VAGRANT_BOX']
  config.vm.box_version = ENV['VAGRANT_BOX_VERSION']
  config.vm.define ENV['VAGRANT_SERVER_NAME']

  ## Configure shared folders
  # config.vm.synced_folder "~/path/to/host/directory", "/full/path/to/vm/directory"

  ## Configure CPU count and RAM
  config.vm.provider "virtualbox" do |v|
    v.name = ENV['VAGRANT_SERVER_NAME']
    v.memory = ENV['VAGRANT_RAM']
    v.cpus = ENV['VAGRANT_CPUS']
  end

  ## Configure SSH
  config.ssh.forward_agent = true
  config.vm.network "forwarded_port", guest: 22, host: ENV["SSH_PORT"], id: "ssh"

  ## Configure forwarded ports
  # config.vm.network "forwarded_port", guest: 80, host: 80, id: "http_server"
end
